[project]
name = "unisport"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = "==3.12.9"
dependencies = [
    "factory-boy==2.12.0",
    "flask==2.3.2",
    "flask-cors==3.0.9",
    "flask-sqlalchemy==2.5.1",
    "gunicorn==20.0.0",
    "prometheus-client==0.11.0",
    "psycopg2==2.9.10",
    "pytest==8.3.5",
    "pytest-cov==2.5.1",
    "sentry-sdk==1.5.8",
    "sqlalchemy==1.4.2",
]
