name: Pytest's test suite
on:
  push:
    branches:
      - master
  pull_request:
env:
  PYTHON_VERSION: 3.9.18
jobs:
  pytest:
    runs-on: ubuntu-latest
    env:
      UV_SYSTEM_PYTHON: 1 # Allow uv to run without virtualenv
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v5
      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - run: uv pip install -r requirements.txt
      - run: pytest .
